hostname: '127.0.0.1'
port: 27017
database: 'hardon'
username: 'dev'
password: 'dev'

sidebar:
  title: '&a&lHardon'
  lines:
    - '&f&m--------------------------------'
    - '&a&lKills: ${kills}'
    - '&a&lDeats: ${deaths}'
    - '&a&lState: ${state}'
    - '&a&lKit: ${kit}'
    - '&f&m--------------------------------'
