hostname: '127.0.0.1'
port: 27017
database: 'hardon'
username: 'dev'
password: 'dev'

sidebar:
  title: '&6&lHardon'
  lines:
    - '&f&m------------------------&r'
    - '&6&lKills: &f${kills}'
    - '&6&lDeats: &f${deaths}'
    - '&6&lState: &f${state}'
    - '&6&lKit: &f${kit}'
    - '&f&m------------------------'
